### ISSUE TITLE
Back Functionality

### ISSUE THREAD

**Issue by joshjung** [kriasoft/universal-router#8]
Hi there. First off, your code is fantastic. I'm loving working with it.

Second, I'm trying to build a default handler for the browser back button. My thought was to have the router have a history array and push the states onto it (with a cap of course) and then if the user pushes the back button I could use the handlePopState event handler, pop the last state off and reapply it. 

I have this all coded up but have a few questions:

1) Were you already working on functionality for this?
2) I can't figure out how to use `npm link react-routing`. When I do, even after doing `npm run-script build` it gives me this error:

    /Users/jjung/dev/web/jd-demos/build/webpack:/src/router.js:4
    import Router from 'react-routing/src/Router';
                       ^
    Error: Cannot find module "react-routing/src/Router"
        at webpackMissingModule (/Users/jjung/dev/web/jd-demos/build/webpack:/src/router.js:4:20)
        at Object.module.exports.Object.defineProperty.value (/Users/jjung/dev/web/jd-    demos/build/webpack:/src/router.js:4:20)
        at __webpack_require__ (/Users/jjung/dev/web/jd-demos/build/webpack:/webpack/bootstrap     14ccd3919092f1554a9b:19:1)
        at Object.<anonymous> (/Users/jjung/dev/web/jd-demos/build/webpack:/src/server.js:9:40)
        at __webpack_require__ (/Users/jjung/dev/web/jd-demos/build/webpack:/webpack/bootstrap     14ccd3919092f1554a9b:19:1)
        at module.exports._this2 (/Users/jjung/dev/web/jd-demos/build/webpack:/webpack/bootstrap 14ccd3919092f1554a9b:39:1)
        at Object.<anonymous> (/Users/jjung/dev/web/jd-demos/build/webpack:/webpack/bootstrap 14ccd3919092f1554a9b:39:1)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)`

**Comment by weblancaster** [comment]
@joshjung looking your log, seems like it's a path issue on not finding the module.

**Comment by Bogdaan** [comment]
@joshjung have you seen https://github.com/rackt/history/blob/master/docs/GettingStarted.md ?

**Comment by frenzzy** [comment]
Old ticket, please reopen if needed.
