### ISSUE TITLE
Nested URL Generation - Cannot set property 'parent' of undefined

### ISSUE THREAD

**Issue by valeeum** [kriasoft/universal-router#89]
I'm getting the following error when I try to generate a url for a nested route.  

router.root.children is getting logged as follows: 

`[ { path: '/:division',
    name: 'division',
    action: [Function: action],
    children: [ undefined ],
    parent: 
     { path: '/',
       name: 'root',
       children: [Circular],
       action: [Function: action],
       parent: null } } ]`

I'm not sure why children: is showing up as `[ undefined ] ` as actual routing is working fine.  My issue is specifically related to url generation.

Stack trace is as follows:

`TypeError: Cannot set property 'parent' of undefined
    at update (/var/www/node_modules/src/generateUrls.js:27:9)
    at update (/var/www/node_modules/universal-router/generateUrls/main.js:30:9)
    at UrlService.url (/var/www/node_modules/universal-router/generateUrls/main.js:39:7)
    at UrlService.getUrl (/var/www/build/webpack:/service/UrlService.js:17:17)
    at Login.render (/var/www/build/webpack:/routes/client/auth/default/Login.js:46:57)
    at /var/www/node_modules/react/lib/ReactCompositeComponent.js:793:21
    at measureLifeCyclePerf (/var/www/node_modules/react/lib/ReactCompositeComponent.js:74:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/var/www/node_modules/react/lib/ReactCompositeComponent.js:792:27)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/var/www/node_modules/react/lib/ReactCompositeComponent.js:819:34)
    at ReactCompositeComponentWrapper.performInitialMount (/var/www/node_modules/react/lib/ReactCompositeComponent.js:361:30)
    at ReactCompositeComponentWrapper.mountComponent (/var/www/node_modules/react/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/var/www/node_modules/react/lib/ReactReconciler.js:47:35)
    at ReactCompositeComponentWrapper.performInitialMount (/var/www/node_modules/react/lib/ReactCompositeComponent.js:370:34)
    at ReactCompositeComponentWrapper.mountComponent (/var/www/node_modules/react/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/var/www/node_modules/react/lib/ReactReconciler.js:47:35)
    at /var/www/node_modules/react/lib/ReactServerRendering.js:46:36
    at ReactServerRenderingTransaction.perform (/var/www/node_modules/react/lib/Transaction.js:138:20)
    at renderToStringImpl (/var/www/node_modules/react/lib/ReactServerRendering.js:44:24)
    at Object.renderToString (/var/www/node_modules/react/lib/ReactServerRendering.js:74:10)
    at _callee$ (/var/www/build/webpack:/server.js:179:30)
    at tryCatch (/var/www/node_modules/regenerator-runtime/runtime.js:63:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/var/www/node_modules/regenerator-runtime/runtime.js:337:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/www/node_modules/regenerator-runtime/runtime.js:96:21)
    at step (/var/www/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /var/www/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)`

**Comment by valeeum** [comment]
nevermind, i dont believe this is an issue with the library.
